set(MCU_FAMILY STM32L0xx)
set(MCU_PART STM32L053xx)
set(MCU_MCPU cortex-m0plus)
set(LINKER_SCRIPT ${CMAKE_SOURCE_DIR}/linker/linkerscript.ld)
set(TOOL_PATH /Users/tommy.philyaw/gcc-arm-none-eabi-6-2017-q2-update/bin)
set(RTOS_TARGET ARM_CM0)
